
export const REAL_API = 'https://api.mirna.cloud/sockets'
//export const REAL_API = 'http://localhost:4000/sockets'
export const RANDOM_USER_API = 'https://randomuser.me/api/?inc=login&noinfo'
export const DURAZNO_WEBSITE = 'https://durazno.io'
export const DURAZNO_NAME = 'Durazno Technologies'
export const CODE_SAMPLE = '/example.txt'
export const SERVER_PROJECT_EXAMPLE = 'https://gist.github.com/marcodali/3a11ed909c864e98cc1639106acdc93f'
export const CLIENT_PROJECT_EXAMPLE = 'https://playcode.io/1604700'
export const LIVE_DEMO_PROJECT_EXAMPLE = 'https://1604700.playcode.io'
